name: Build and test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v5
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint validation
        run: pnpm lint
      - name: Test
        run: pnpm test
